//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Authorities = new HashSet<Authority>();
            this.BranchOfficeReceipts = new HashSet<BranchOfficeReceipt>();
            this.Bills = new HashSet<Bill>();
            this.ProposeReceipts = new HashSet<ProposeReceipt>();
            this.HeadquaterReceipts = new HashSet<HeadquaterReceipt>();
        }
    
        public string AccountID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string CMND { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Authority> Authorities { get; set; }
        public virtual ICollection<BranchOfficeReceipt> BranchOfficeReceipts { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<ProposeReceipt> ProposeReceipts { get; set; }
        public virtual ICollection<HeadquaterReceipt> HeadquaterReceipts { get; set; }
    }
}
