//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public string BillID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int POS { get; set; }
        public double TotalAmount { get; set; }
        public int TotalQuantity { get; set; }
        public double InputMoney { get; set; }
        public double OutputMoney { get; set; }
        public string AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<BillDetail> BillDetails { get; set; }
    }
}
