//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadquaterReceipt
    {
        public HeadquaterReceipt()
        {
            this.BranchOfficeReceipts = new HashSet<BranchOfficeReceipt>();
            this.HeadquaterReceiptDetails = new HashSet<HeadquaterReceiptDetail>();
        }
    
        public string HeadquaterID { get; set; }
        public string ProposeID { get; set; }
        public System.DateTime Date { get; set; }
        public double TotalAmount { get; set; }
        public string AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<BranchOfficeReceipt> BranchOfficeReceipts { get; set; }
        public virtual ICollection<HeadquaterReceiptDetail> HeadquaterReceiptDetails { get; set; }
        public virtual ProposeReceipt ProposeReceipt { get; set; }
    }
}
