//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.BranchOfficeReceiptDetails = new HashSet<BranchOfficeReceiptDetail>();
            this.Prices = new HashSet<Price>();
            this.ProposeReceiptDetails = new HashSet<ProposeReceiptDetail>();
            this.Promotions = new HashSet<Promotion>();
        }
    
        public string ProductID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string SupplierID { get; set; }
        public string CategoryID { get; set; }
    
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual ICollection<BranchOfficeReceiptDetail> BranchOfficeReceiptDetails { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<ProposeReceiptDetail> ProposeReceiptDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
