//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposeReceipt
    {
        public ProposeReceipt()
        {
            this.HeadquaterReceipts = new HashSet<HeadquaterReceipt>();
            this.ProposeReceiptDetails = new HashSet<ProposeReceiptDetail>();
        }
    
        public string ProposeID { get; set; }
        public System.DateTime ProposeDate { get; set; }
        public string SupplierID { get; set; }
        public string AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<HeadquaterReceipt> HeadquaterReceipts { get; set; }
        public virtual ICollection<ProposeReceiptDetail> ProposeReceiptDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
